Adding buyer to `Order` model
simonfabcic/32_-_NestJS_-_ReactJS-app pull request #48
Opened 2024-07-09 12:11 UTC by simonfabcic

[What?]
Adding `buyer` to order.

[Why?]
Buyer is the main field of the order.
When rendering orders on the frontend, I want to show to which user it belongs.

[How?]
- Adding the `buyer` field (required) to the `Order` model
- In serializers, I added an option, that in the returned JSON is
    - whole `Product`, not just ID
    - whole `ShopProfile`, not just ID

[Testing?]
Into existing tests, I added `ShopProfile` where `Order` is created or updated.

2024-07-09 12:56 UTC, jurecuhalev commented on backend/shop/models.py
> +    buyer = models.ForeignKey(ShopProfile, on_delete=models.CASCADE, null=False)
https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.Field.null

null=False, is already default. No need to specify it.

2024-07-09 12:57 UTC, jurecuhalev commented on backend/shop/tests/test_models.py
> +        self.shopProfile = ShopProfileFactory()
`self.shop_profile` - follow https://peps.python.org/pep-0008/#descriptive-naming-styles

2024-07-09 18:13 UTC, petmetic requested changes
I would recommend you write out your desired `.json` file and try to make minimal canges to te code.

2024-07-09 18:13 UTC, petmetic commented on backend/shop/serializers.py
read_only = ["order"]

Ten tink about if you really need order = PrimaryRelatedField(). Try wit read_only and ten see wat you get. If it does not work, look for te least-code solution.


mapping fields: https://www.django-rest-framework.org/api-guide/serializers/#customizing-field-mappings

2024-07-10 11:32 UTC, simonfabcic commented on backend/shop/serializers.py
Hu, I can't figure out, what you mean...
I added `to_representation`, because the output was not in the desired format.

Maybe I don't konw enough about REST... :/

2024-07-10 11:58 UTC, simonfabcic reviewed
Changes from the last PR:
- renamed variable `shopProfile` to `shop_profile`
- changed `admin.site.register(...)` that is not list but separated 
- deleted `null=False` in the model field definition because this is the default state

2024-07-10 14:31 UTC, jurecuhalev commented on backend/shop/serializers.py
What output did you get and what did you want to get?

2024-07-10 18:42 UTC, simonfabcic commented
I get (this is code without `to_representation` methods):
```
{
        "id": 4,
        "order_items": [
            {
                "id": 1,
                "order": 4,
                "product": 29,
                "quantity": 3
            },
            {
                "id": 4,
                "order": 4,
                "product": 30,
                "quantity": 5
            }
        ],
        "buyer": 8
    },
```
I want:
```
    {
        "id": 4,
        "order_items": [
            {
                "id": 1,
                "order": 4,
                "product": {
                    "id": 29,
                    "image": null,
                    "title": "naslov izdelka",
                    "description": "",
                    "price": "2233.00"
                },
                "quantity": 3
            },
            {
                "id": 4,
                "order": 4,
                "product": {
                    "id": 30,
                    "image": null,
                    "title": "Aljoševa torba",
                    "description": "",
                    "price": "100.00"
                },
                "quantity": 5
            }
        ],
        "buyer": {
            "id": 8,
            "email": "michael.jones@email.com",
            "full_name": "Michael Jones",
            "first_name": "Michael",
            "last_name": "Jones",
            "username": "michael.jones@email.com",
            "avatar": null,
            "groups": []
        }
    },
```

2024-07-10 19:33 UTC, petmetic commented
Try achieving the output wit nested serializers...
https://www.django-rest-framework.org/api-guide/relations/#nested-relationships

2024-07-11 18:59 UTC, merged